---
title: "Task_1_Gladyshev"
author: "Hayrest"
date: "2024-08-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library (readr)
library(tibble)
library (tidyr)
library (dplyr)
```

## R Markdown

#tibble(), tidyr and dplyr

```{r}


data %>% add_column(column_name = 1:10, .before = NULL, .after = NULL)

data %>% add_row(var_1 = 1, var_2 = "value", .before = NULL, .after = NULL)

data_1 %>% bind_cols(data_2) %>% bind_cols(data_3)

data_1 %>% bind_rows(data_2) %>% bind_rows(data_3)

data_1 <- tibble(var_1 = 1:8) %>% mutate(id = row_number())

data_2 <- tibble(var_2 = rnorm(10)) %>% mutate(`Subject ID` = row_number())

data %>% group_by(column_name)
```

#First lession with dataset

```{r}
data <- read_tsv("https://stepik.org/media/attachments/lesson/790863/data_tsv.tsv")

data %>%
  select (`Группа крови`, `Рост`)

data %>%
  select (`Группа крови`, `Рост`)

data %>% 
  select (where (is.numeric))

data %>% select (`Группа`, where (is.numeric))

data %>%
  select(`Группа`, where(is.numeric)) %>%
  select_if(~ mean(.x, na.rm = TRUE) > 10)




```

#Функция для расчета списка статистик

```{r}
statistics <- list(
      `Количество субъектов` = ~length(.x),
      `Количество (есть данные)` = ~sum(!is.na(.x)),
      `Нет данных` = ~sum(is.na(.x)),
      `Ср. знач.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Станд. отклон.` = ~ifelse(sum(!is.na(.x)) < 3, "Н/П*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `95% ДИ для среднего` = ~sd(.x, na.rm = TRUE) %>% round(2) %>% as.character(),
      `мин. - макс.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2))),
      `Медиана` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2)))
)

data %>%
  select(`Группа`, where(is.numeric)) %>%
  group_by(`Группа`) %>% 
  summarise(across(where(is.numeric), statistics)) %>%
  mutate(across(everything(), as.character)) %>%  # Преобразование в character
  pivot_longer(!`Группа`) %>%
  separate(name, into = c("Переменная", "Статистика"), sep = "__") %>% 
  rename(`Значение` = value)



```



